### ISSUE TITLE
Crawling on SteamDB does not work anymore

### ISSUE THREAD

**Issue by etaxi341** [etaxi341/FreeSteamGames-TelegramBot#5]
SteamDB stopped crawling of the Free Games with Cloudflare Captcha. Have to find a new way to crawl...

**Comment by etaxi341** [comment]
Thank you for fixing @RallyTuning in PR #6 

Did not know about those official links form valve.

**Comment by RallyTuning** [comment]
You can spot them by looking at the js page using Chrome console. I believe there are more params that you the game details in the first call, instead of only the name and the link, but i am no so sure, must dig better.
For anyone who read, do not call them in a short time loop or Valve will notice the high (useless) traffic and block the connection. 1 check every 60/45 min will be ok. Free deals doesn't change so quickly, they usually change after days
